<?php

/**
 * BaseBatiment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $niveau
 * @property integer $id_ville
 * @property string $theme
 * @property Ville $Ville
 * 
 * @method integer  getId()       Returns the current record's "id" value
 * @method string   getName()     Returns the current record's "name" value
 * @method integer  getNiveau()   Returns the current record's "niveau" value
 * @method integer  getIdVille()  Returns the current record's "id_ville" value
 * @method string   getTheme()    Returns the current record's "theme" value
 * @method Ville    getVille()    Returns the current record's "Ville" value
 * @method Batiment setId()       Sets the current record's "id" value
 * @method Batiment setName()     Sets the current record's "name" value
 * @method Batiment setNiveau()   Sets the current record's "niveau" value
 * @method Batiment setIdVille()  Sets the current record's "id_ville" value
 * @method Batiment setTheme()    Sets the current record's "theme" value
 * @method Batiment setVille()    Sets the current record's "Ville" value
 * 
 * @package    unramalak
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBatiment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('batiment');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('niveau', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('id_ville', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('theme', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ville', array(
             'local' => 'id_ville',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}