<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property date $birthday
 * @property string $title
 * @property string $avatar
 * @property integer $id_race
 * @property sfGuardUser $User
 * @property Race $Race
 * 
 * @method integer            getId()       Returns the current record's "id" value
 * @method integer            getUserId()   Returns the current record's "user_id" value
 * @method date               getBirthday() Returns the current record's "birthday" value
 * @method string             getTitle()    Returns the current record's "title" value
 * @method string             getAvatar()   Returns the current record's "avatar" value
 * @method integer            getIdRace()   Returns the current record's "id_race" value
 * @method sfGuardUser        getUser()     Returns the current record's "User" value
 * @method Race               getRace()     Returns the current record's "Race" value
 * @method sfGuardUserProfile setId()       Sets the current record's "id" value
 * @method sfGuardUserProfile setUserId()   Sets the current record's "user_id" value
 * @method sfGuardUserProfile setBirthday() Sets the current record's "birthday" value
 * @method sfGuardUserProfile setTitle()    Sets the current record's "title" value
 * @method sfGuardUserProfile setAvatar()   Sets the current record's "avatar" value
 * @method sfGuardUserProfile setIdRace()   Sets the current record's "id_race" value
 * @method sfGuardUserProfile setUser()     Sets the current record's "User" value
 * @method sfGuardUserProfile setRace()     Sets the current record's "Race" value
 * 
 * @package    unramalak
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('birthday', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('title', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('avatar', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('id_race', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Race', array(
             'local' => 'id_race',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_timestampable();
        $this->actAs($timestampable0);
    }
}