<?php

/**
 * BaseCell
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $position_x
 * @property integer $position_y
 * @property string $background_image
 * @property integer $id_type
 * @property integer $id_map
 * @property Map $Map
 * 
 * @method integer getId()               Returns the current record's "id" value
 * @method integer getPositionX()        Returns the current record's "position_x" value
 * @method integer getPositionY()        Returns the current record's "position_y" value
 * @method string  getBackgroundImage()  Returns the current record's "background_image" value
 * @method integer getIdType()           Returns the current record's "id_type" value
 * @method integer getIdMap()            Returns the current record's "id_map" value
 * @method Map     getMap()              Returns the current record's "Map" value
 * @method Cell    setId()               Sets the current record's "id" value
 * @method Cell    setPositionX()        Sets the current record's "position_x" value
 * @method Cell    setPositionY()        Sets the current record's "position_y" value
 * @method Cell    setBackgroundImage()  Sets the current record's "background_image" value
 * @method Cell    setIdType()           Sets the current record's "id_type" value
 * @method Cell    setIdMap()            Sets the current record's "id_map" value
 * @method Cell    setMap()              Sets the current record's "Map" value
 * 
 * @package    unramalak
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCell extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cell');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('position_x', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('position_y', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('background_image', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('id_type', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('id_map', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Map', array(
             'local' => 'id_map',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}