<?php

/**
 * BaseMap
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $height
 * @property integer $width
 * @property integer $starting_cell_id
 * @property Doctrine_Collection $Cell
 * @property Cell $Starting_Cell
 * @property Doctrine_Collection $Heros
 * @property Doctrine_Collection $Position
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getName()             Returns the current record's "name" value
 * @method integer             getHeight()           Returns the current record's "height" value
 * @method integer             getWidth()            Returns the current record's "width" value
 * @method integer             getStartingCellId()   Returns the current record's "starting_cell_id" value
 * @method Doctrine_Collection getCell()             Returns the current record's "Cell" collection
 * @method Cell                getStartingCell()     Returns the current record's "Starting_Cell" value
 * @method Doctrine_Collection getHeros()            Returns the current record's "Heros" collection
 * @method Doctrine_Collection getPosition()         Returns the current record's "Position" collection
 * @method Map                 setId()               Sets the current record's "id" value
 * @method Map                 setName()             Sets the current record's "name" value
 * @method Map                 setHeight()           Sets the current record's "height" value
 * @method Map                 setWidth()            Sets the current record's "width" value
 * @method Map                 setStartingCellId()   Sets the current record's "starting_cell_id" value
 * @method Map                 setCell()             Sets the current record's "Cell" collection
 * @method Map                 setStartingCell()     Sets the current record's "Starting_Cell" value
 * @method Map                 setHeros()            Sets the current record's "Heros" collection
 * @method Map                 setPosition()         Sets the current record's "Position" collection
 * 
 * @package    unramalak
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMap extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('map');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('height', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('width', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('starting_cell_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Cell', array(
             'local' => 'id',
             'foreign' => 'id_map'));

        $this->hasOne('Cell as Starting_Cell', array(
             'local' => 'starting_cell_id',
             'foreign' => 'id'));

        $this->hasMany('Heros', array(
             'local' => 'id',
             'foreign' => 'id_map'));

        $this->hasMany('Position', array(
             'local' => 'id',
             'foreign' => 'id_map'));
    }
}