<?php

/**
 * BaseCell_Type
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $name
 * @property string $background_image
 * @property integer $id_type_family
 * @property Cell_Type_Family $Cell_Type_Family
 * 
 * @method integer          getId()               Returns the current record's "id" value
 * @method varchar          getName()             Returns the current record's "name" value
 * @method string           getBackgroundImage()  Returns the current record's "background_image" value
 * @method integer          getIdTypeFamily()     Returns the current record's "id_type_family" value
 * @method Cell_Type_Family getCellTypeFamily()   Returns the current record's "Cell_Type_Family" value
 * @method Cell_Type        setId()               Sets the current record's "id" value
 * @method Cell_Type        setName()             Sets the current record's "name" value
 * @method Cell_Type        setBackgroundImage()  Sets the current record's "background_image" value
 * @method Cell_Type        setIdTypeFamily()     Sets the current record's "id_type_family" value
 * @method Cell_Type        setCellTypeFamily()   Sets the current record's "Cell_Type_Family" value
 * 
 * @package    unramalak
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCell_Type extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cell_type');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'varchar', 50, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('background_image', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('id_type_family', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cell_Type_Family', array(
             'local' => 'id_type_family',
             'foreign' => 'id'));
    }
}