<?php

/**
 * BaseAttributes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $life
 * @property integer $life_max
 * @property integer $mana
 * @property integer $mana_max
 * @property integer $limit_lvl
 * @property integer $limit_max
 * @property integer $strength
 * @property integer $agility
 * @property integer $intelligence
 * @property integer $id_heros
 * @property Heros $Heros
 * 
 * @method integer    getId()           Returns the current record's "id" value
 * @method integer    getLife()         Returns the current record's "life" value
 * @method integer    getLifeMax()      Returns the current record's "life_max" value
 * @method integer    getMana()         Returns the current record's "mana" value
 * @method integer    getManaMax()      Returns the current record's "mana_max" value
 * @method integer    getLimitLvl()     Returns the current record's "limit_lvl" value
 * @method integer    getLimitMax()     Returns the current record's "limit_max" value
 * @method integer    getStrength()     Returns the current record's "strength" value
 * @method integer    getAgility()      Returns the current record's "agility" value
 * @method integer    getIntelligence() Returns the current record's "intelligence" value
 * @method integer    getIdHeros()      Returns the current record's "id_heros" value
 * @method Heros      getHeros()        Returns the current record's "Heros" value
 * @method Attributes setId()           Sets the current record's "id" value
 * @method Attributes setLife()         Sets the current record's "life" value
 * @method Attributes setLifeMax()      Sets the current record's "life_max" value
 * @method Attributes setMana()         Sets the current record's "mana" value
 * @method Attributes setManaMax()      Sets the current record's "mana_max" value
 * @method Attributes setLimitLvl()     Sets the current record's "limit_lvl" value
 * @method Attributes setLimitMax()     Sets the current record's "limit_max" value
 * @method Attributes setStrength()     Sets the current record's "strength" value
 * @method Attributes setAgility()      Sets the current record's "agility" value
 * @method Attributes setIntelligence() Sets the current record's "intelligence" value
 * @method Attributes setIdHeros()      Sets the current record's "id_heros" value
 * @method Attributes setHeros()        Sets the current record's "Heros" value
 * 
 * @package    unramalak
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAttributes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('attributes');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('life', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('life_max', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('mana', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('mana_max', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('limit_lvl', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('limit_max', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('strength', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('agility', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('intelligence', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_heros', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Heros', array(
             'local' => 'id_heros',
             'foreign' => 'id'));
    }
}