<?php

/**
 * BasePosition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $position_x
 * @property integer $position_y
 * @property integer $id_map
 * @property Map $Map
 * 
 * @method integer  getId()         Returns the current record's "id" value
 * @method integer  getPositionX()  Returns the current record's "position_x" value
 * @method integer  getPositionY()  Returns the current record's "position_y" value
 * @method integer  getIdMap()      Returns the current record's "id_map" value
 * @method Map      getMap()        Returns the current record's "Map" value
 * @method Position setId()         Sets the current record's "id" value
 * @method Position setPositionX()  Sets the current record's "position_x" value
 * @method Position setPositionY()  Sets the current record's "position_y" value
 * @method Position setIdMap()      Sets the current record's "id_map" value
 * @method Position setMap()        Sets the current record's "Map" value
 * 
 * @package    unramalak
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePosition extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('position');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('position_x', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('position_y', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_map', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Map', array(
             'local' => 'id_map',
             'foreign' => 'id'));
    }
}