<?php

/**
 * BaseVille
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $capital
 * @property string $taille
 * @property integer $id_planete
 * @property Planete $Planete
 * @property Doctrine_Collection $Batiment
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method integer             getCapital()    Returns the current record's "capital" value
 * @method string              getTaille()     Returns the current record's "taille" value
 * @method integer             getIdPlanete()  Returns the current record's "id_planete" value
 * @method Planete             getPlanete()    Returns the current record's "Planete" value
 * @method Doctrine_Collection getBatiment()   Returns the current record's "Batiment" collection
 * @method Ville               setId()         Sets the current record's "id" value
 * @method Ville               setName()       Sets the current record's "name" value
 * @method Ville               setCapital()    Sets the current record's "capital" value
 * @method Ville               setTaille()     Sets the current record's "taille" value
 * @method Ville               setIdPlanete()  Sets the current record's "id_planete" value
 * @method Ville               setPlanete()    Sets the current record's "Planete" value
 * @method Ville               setBatiment()   Sets the current record's "Batiment" collection
 * 
 * @package    unramalak
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVille extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ville');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('capital', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('taille', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('id_planete', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Planete', array(
             'local' => 'id_planete',
             'foreign' => 'id'));

        $this->hasMany('Batiment', array(
             'local' => 'id',
             'foreign' => 'id_ville'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}