<?php

/**
 * BaseItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $history
 * @property string $description
 * @property string $thumbnail
 * @property string $real_image
 * @property integer $is_original
 * 
 * @method integer getId()          Returns the current record's "id" value
 * @method string  getName()        Returns the current record's "name" value
 * @method string  getHistory()     Returns the current record's "history" value
 * @method string  getDescription() Returns the current record's "description" value
 * @method string  getThumbnail()   Returns the current record's "thumbnail" value
 * @method string  getRealImage()   Returns the current record's "real_image" value
 * @method integer getIsOriginal()  Returns the current record's "is_original" value
 * @method Item    setId()          Sets the current record's "id" value
 * @method Item    setName()        Sets the current record's "name" value
 * @method Item    setHistory()     Sets the current record's "history" value
 * @method Item    setDescription() Sets the current record's "description" value
 * @method Item    setThumbnail()   Sets the current record's "thumbnail" value
 * @method Item    setRealImage()   Sets the current record's "real_image" value
 * @method Item    setIsOriginal()  Sets the current record's "is_original" value
 * 
 * @package    unramalak
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('item');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('history', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('thumbnail', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('real_image', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('is_original', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}