<?php

/**
 * BaseCell_Type_Family
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $name
 * @property string $background_image
 * @property Doctrine_Collection $Cell_Type
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method varchar             getName()             Returns the current record's "name" value
 * @method string              getBackgroundImage()  Returns the current record's "background_image" value
 * @method Doctrine_Collection getCellType()         Returns the current record's "Cell_Type" collection
 * @method Cell_Type_Family    setId()               Sets the current record's "id" value
 * @method Cell_Type_Family    setName()             Sets the current record's "name" value
 * @method Cell_Type_Family    setBackgroundImage()  Sets the current record's "background_image" value
 * @method Cell_Type_Family    setCellType()         Sets the current record's "Cell_Type" collection
 * 
 * @package    unramalak
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCell_Type_Family extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cell_type_family');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'varchar', 50, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('background_image', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Cell_Type', array(
             'local' => 'id',
             'foreign' => 'id_type_family'));
    }
}