_welcome:
  pattern:  /
  defaults: { _controller: KrovitchBundle:Krovitch:index }

_demo_secured:
  resource: "@AcmeDemoBundle/Controller/SecuredController.php"
  type:     annotation

_demo:
  resource: "@AcmeDemoBundle/Controller/DemoController.php"
  type:     annotation
  prefix:   /demo

_assetic:
  resource: .
  type:     assetic



_test:
  resource: "@KrovitchBundle/Controller/KrovitchController.php"
  type:     annotation

_content:
  resource: "@KrovitchBundle/Controller/ContentController.php"
  type:     annotation

_map:
  resource: "@KrovitchBundle/Controller/MapController.php"
  type:     annotation