<?php

namespace Krovitch\KrovitchBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitRepository extends EntityRepository
{
}
