<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/16 00:19:20
sfConfig::add(array(
  'app_menu_plugin_default_route' => '@homepage',
  'app_editor_pointers' => array (
  0 => 
  array (
    'label' => 'Petit',
    'size' => 0,
  ),
  1 => 
  array (
    'label' => 'Moyen',
    'size' => 1,
  ),
  2 => 
  array (
    'label' => 'Grand',
    'size' => 2,
  ),
),
  'app_editor_map_size' => '8x9',
  'app_map_absolute_path' => '/home/afrezet/workspace/unramalak_symfony/web/uploads/maps',
  'app_map_path' => '/apps/frontend/modules/map/xml/',
  'app_map_images_path' => 'map/backgrounds/',
  'app_map_map_test' => 'map_test.xml',
  'app_map_polygon_line_size' => 20,
  'app_sf_guard_plugin_routes_register' => true,
  'app_sf_guard_plugin_profile_class' => 'sfGuardUserProfile',
  'app_sf_guard_plugin_profile_field_name' => 'user_id',
  'app_menu' => array (
  'accueil' => 
  array (
    'link' => '@homepage',
    'label' => 'Accueil',
  ),
  'map' => 
  array (
    'link' => '@map',
    'label' => 'Map',
    'is_secure' => true,
  ),
  'backend' => 
  array (
    'link' => '@homepage',
    'label' => 'Backoffice',
    'application' => 'backend',
  ),
),
  'app_global_config_input_max_length' => 50,
  'app_zaloumek_start_limit_level' => 5,
  'app_zaloumek_start_map_id' => 1,
  'app_path_avatar' => 'avatar',
  'app_path_banniere' => 'banniere',
  'app_images_avatars' => array (
  0 => 'sophie.png',
  1 => 'cha.png',
),
  'app_xp_xp_update_coefficient' => 1.2,
  'app_xp_xp_start' => 50,
));
