<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/11/16 00:19:20

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=unramalak',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
