<?php

/**
 * ArmyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArmyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArmyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Army');
    }
}