<?php

/**
 * CellTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CellTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return CellTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('Cell');
  }

  public function updateCell($cell_data)
  {
    return $this->createQuery('c')
      ->update('Cell c')
      ->set('c.id_type', '?', $cell_data->id_type)
      ->set('c.background_image', '?', $cell_data->background_image)
      ->where('c.id = ?', intval($cell_data->id))
      ->execute();
  }

  /**
   * 
   * Enter description here ...
   * @param unknown_type $id_map
   * @param Point $starting_point
   * @param Point $ending_point
   * @return \Doctrine_Collection
   */
  public function getCellsBetweenPosition($id_map, Point $starting_point, Point $ending_point)
  {
    return $this->createQuery('c')
      ->where('c.id_map = ?', $id_map)
      ->andWhere('c.position_x >= ?', $starting_point->getX())
      ->andWhere('c.position_y >= ?', $starting_point->getY())
      ->andWhere('c.position_x <= ?', $ending_point->getX())
      ->andWhere('c.position_y <= ?', $ending_point->getX())
      ->orderBy('c.position_y, c.position_x')
      ->execute();    
  }

  public function getCellByPosition($id_map, Point $point)
  {
    return $this->createQuery('c')
    ->where('c.id_map = ?', $id_map)
    ->andWhere('c.position_x = ?', $point->getX())
    ->andWhere('c.position_y = ?', $point->getY())
    ->fetchOne();
  }
  
  /*public function getLastCell($id_map)
  {
    $max_cell = $this->createQuery('c1')
      ->select('MAX(c1.position_x) AS max_x, MAX(c1.position_y) AS max_y')
      ->where('c1.id_map = ?', $id_map)
      ->execute(null, Doctrine::HYDRATE_ARRAY);
    
    return $this->createQuery('c')
     ->where('c1.id_map = ?', $id_map)
     ->andWhere('c.position_x = ?', $max_cell['max_x'])
     ->andWhere('c.position_y = ?', $max_cell['max_y'])
     ->execute();
  }*/
}