<?php

/**
 * Cell_Type_Family
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    unramalak
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Cell_Type_Family extends BaseCell_Type_Family
{
}