<?php

/**
 * Cell_Type_FamilyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Cell_Type_FamilyTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return Cell_Type_FamilyTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Cell_Type_Family');
  }

  /**
   * @return Doctrine_Collection
   */
  public function getFamiliesWithCellType()
  {
    return $this->createQuery('f')
      ->leftJoin('f.CellType c')
      ->execute();
  }
}