<?php

/**
 * Cell_TypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Cell_TypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return Cell_TypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cell_Type');
    }
}