<?php

/**
 * Cell
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    unramalak
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Cell extends BaseCell
{
  /*public function render()
  {
    $content = '<span class="cell">';
    $content.= image_tag($this->getBackgroundImage(), array('alt' => 'map-cell'));
    $content.= '</span>';

    return $content;
  }

  public static function getCellsArray($cells)
  {
    $cell_array = array();
    $width = $size['width'];
    $height = $size['height'];

    for($x = 0; $x < $width; $x++){
      $cell_array[$x] = array();
      for($y = 0; $y < $height; $y++){
        $cell_array[$x][$y] = new self($x, $y);
      }
    }
    return $cell_array;
  }*/

  public function getPoint()
  {
    return new Point($this->getPositionX(), $this->getPositionY());
  }
  
  /*public function getLimitPoint()
  {
    
  }*/
}
