<?php

/**
 * HerosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HerosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HerosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Heros');
    }
}