<?php

/**
 * Map
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    unramalak
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Map extends BaseMap
{
  public function render(Point $starting_point, Point $ending_point)
	{
	  $content = '<table id="map-table" cellpadding="0" cellspacing="0">';
	  $last_row = -1;
	  $cells = CellTable::getInstance()->getCellsBetweenPosition($this->getId(), $starting_point, $ending_point);
	  
	  foreach($cells as $cell){
	    if($cell->getPositionY() > $last_row){
	      $last_row = $cell->getPositionY();
	      $content.= '<tr>';
	    }	    
	    $content.= '<td>';	    
	    $content.= $cell->render();
	    $content.= '</td>';
	    
	    if($cell->getPositionY() > $last_row){
	      $content.= '</tr>';
	    }	    
	  }
	  $content.= '</table>';
	  
	  return $content;
	}
	
	public function getStartingCell()
	{
	  return CellTable::getInstance()->find($this->getStartingCellId());
	}
	
	public function getEndingCell(Point $point, $limit)
	{
	  $ending_point = new Point($point->getX() + $limit[0], $point->getY() + $limit[1]);
	  $ending_cell = CellTable::getInstance()->getCellByPosition($this->getId(), $ending_point);
	  
	  if(!$ending_cell){
	    $ending_cell = CellTable::getInstance()->getLastCell($this_>getId());
	  }
	  
	  return $ending_cell;
	}
}