<?php

/**
 * MapTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MapTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return MapTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Map');
  }

  public function getMapWithDatas()
  {
    return $this->createQuery('m')
      ->leftJoin('m.Cells c')
      ->execute();
  }
}