<?php

/**
 * RaceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RaceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RaceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Race');
    }
}