default:
  http_metas:
    content-type: text/html

  metas:
    title:        UnRamalaK beta 0.1
    description:  UnRamalaK beta 0.1
    keywords:     UnRamalaK, jeux, univers, civilisation, symfony
    language:     fr
    robots:       index, follow

  stylesheets:    [main, jquery-ui, unramalakPlugin]

  javascripts:
    - jquery/jquery
    - jquery/jquery-ui.min
    - jquery/jquery.maskedinput.min
    - jquery/jquery.class
    - jquery/jquery.background-position
    - main
    - /unramalakPlugin/js/unramalak
    - /unramalakPlugin/js/map
    - /unramalakPlugin/js/map.canvas
 
  has_layout:     on
  layout:         layout