# @homepage
homepage:
  url:   /
  param: { module: homepage, action: index }
  
# @backend
backend:
  url: /backend_dev.php

# sfGuard
signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin } 
signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout } 
password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

# new player  
new_player:
  url:   /new_player
  param: { module: profile, action: new }
    
heros:
  url:   /heros
  param: { module: heros, action: edit }
  
# map
map:
  url:   /map
  param: { module: map, action: index }
  
new_map:
  url:   /map/new
  param: { module: map, action: new }
  
delete_map:
  url:  /map/delete
  param: { module: map, action: delete }
  
edit_map:
  url:  /map/edit
  param: { module: map, action: edit }

save_map:
  url: /map/save
  param: { module: map, action: save }