default:
  http_metas:
    content-type: text/html

  metas:
    title:        UnRamalaK beta 1.0
    description:  UnRamalaK beta 1.0
    keywords:     symfony, project, UnRamalaK
    language:     fr
    robots:       index, follow

  stylesheets:    [main, jquery-ui, unramalakPlugin]

  javascripts:    [jquery/jquery.min, jquery/jquery-ui.min, jquery/jquery.maskedinput.min, jquery/jquery.class, jquery/jquery.background-position.js, /unramalakPlugin/js/unramalak.js]
 
  has_layout:     on
  layout:         layout