# Unramalak
_welcome:
  pattern:  /
  defaults: { _controller: UnramalakBundle:Krovitch:index }

_home:
  resource: "@UnramalakBundle/Controller/KrovitchController.php"
  type:     annotation

_map:
  resource: "@UnramalakBundle/Controller/MapController.php"
  type:     annotation

_editor:
  resource: "@UnramalakBundle/Controller/EditorController.php"
  type:     annotation

_tests:
  resource: "@UnramalakBundle/Controller/TestsController.php"
  type:     annotation

_medias:
  resource: "@UnramalakBundle/Controller/MediaController.php"
  type:     annotation

# UserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile