_welcome:
  pattern:  /
  defaults: { _controller: KrovitchBundle:Krovitch:index }

_test:
  resource: "@KrovitchBundle/Controller/KrovitchController.php"
  type:     annotation

_content:
  resource: "@KrovitchBundle/Controller/ContentController.php"
  type:     annotation

_map:
  resource: "@KrovitchBundle/Controller/MapController.php"
  type:     annotation

_editor:
    resource: "@KrovitchBundle/Controller/EditorController.php"
    type:   annotation

# UserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile