parameters:
    # managers
    krovitch.content_manager.class: Krovitch\KrovitchBundle\Manager\ContentManager
    krovitch.hero_manager.class: Krovitch\KrovitchBundle\Manager\HeroManager
    krovitch.map_manager.class: Krovitch\KrovitchBundle\Manager\MapManager
    krovitch.media_manager.class: Krovitch\KrovitchBundle\Manager\MapManager
    # listeners
    sensio_framework_extra.view.listener.class: Krovitch\BaseBundle\Listener\ParametersTemplateListener
    krovitch.listener.preExecute.class: Krovitch\BaseBundle\Listener\ControllerPreExecuteListener

services:
#    imprinet_back_office.example:
#        class: %imprinet_back_office.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    # listener
#    controller.pre_execute_listener:
#        class: Imprinet\BackOfficeBundle\Listener\ControllerPreExecuteListener
#        tags:
#            - {name: kernel.event_listener, event: kernel.controller, method: onCoreController}

    # managers
    imprinet.job_manager:
        class: Imprinet\BackOfficeBundle\Manager\JobManager
        arguments: [@doctrine.orm.entity_manager, 'service']

    # managers
    krovitch.content_manager:
        class: %krovitch.content_manager.class%
        arguments: [@doctrine.orm.entity_manager, 'service']
    krovitch.hero_manager:
        class: %krovitch.hero_manager.class%
        arguments: [@doctrine.orm.entity_manager, 'service']
    krovitch.map_manager:
        class: %krovitch.map_manager.class%
        arguments: [@doctrine.orm.entity_manager, 'service']
    krovitch.media_manager:
        class: %krovitch.media_manager.class%
        arguments: [@doctrine.orm.entity_manager, 'service']

    # login form
    krovitch_user.registration.form.type:
        class: Krovitch\KrovitchUserBundle\Form\RegistrationFormType
        arguments: ['plain_value', %fos_user.model.user.class%]
        tags:
            - {name: form.type, alias: krovitch_user_registration}
    # preExecute hook
    controller.pre_execute_listener:
        class: %krovitch.listener.preExecute.class%
        tags:
            - {name: kernel.event_listener, event: kernel.controller, method: onCoreController}