homepage:
    path:  "/"
    defaults: { _controller: KrovitchUnramalakFrontBundle:Home:index }

register:
    path:  "/register"
    defaults: { _controller: KrovitchUnramalakFrontBundle:Home:register }

hero.create:
    path: "/hero/creation"
    defaults: { _controller: KrovitchUnramalakFrontBundle:Hero:create }