<?php

/**
 * BatimentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BatimentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BatimentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Batiment');
    }
}