<?php

namespace Krovitch\UnramalakBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HeroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeroRepository extends EntityRepository
{
}
