all:
  # map configuration
  map:
    absolute_path: "%sf_upload_dir%/maps"

    path: /apps/frontend/modules/map/xml/
    images_path: map/backgrounds/
    map_test: map_test.xml
    
    polygon_line_size: 20 # taille de l'arete des polygones
    
  editor:
    map_size: 8x9 # width x heigth, including cache