admin:
    path:  "/admin"
    defaults: { _controller: KrovitchUnramalakBundle:Admin:index }

admin_action:
    path:  "/admin/{action}/{entity}/{id}"
    defaults: { _controller: KrovitchUnramalakBundle:Admin:execute, id: 0, entity: 0 }