### MAPS ###
# url that allow to play map for testing purpose (only in admin)
map.test:
    path:  "/admin/map/test/{id}"
    defaults: { _controller: KrovitchUnramalakBundle:Map:test}

map.regenerate:
    path:  "/map/regenerate/{id}"
    defaults: { _controller: KrovitchUnramalakBundle:Map:regenerate}

unramalak.map.save:
    path: /map/save
    defaults: { _controller: KrovitchUnramalakBundle:Map:save}

###########

admin:
    path:  "/admin"
    defaults: { _controller: KrovitchUnramalakBundle:Admin:index }

admin_action:
    path:  "/admin/{action}/{entity}/{id}"
    defaults: { _controller: KrovitchUnramalakBundle:Admin:execute, id: 0, entity: 0 }