parameters:
    # converter
    unramalak.map.transformer: Krovitch\UnramalakBundle\Map\Transformer\JsonTransformer

services:
    # map transformer
    unramalak.map.transformer:
        class: %unramalak.map.transformer%
        arguments: [@unramalak.manager.map, @unramalak.manager.land]

imports:
    - { resource: forms.yml }
    - { resource: managers.yml }