<?php

/**
 * AttributesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AttributesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AttributesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Attributes');
    }
}