<?php

/**
 * CellTypeFamilyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CellTypeFamilyTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return CellTypeFamilyTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('CellTypeFamily');
  }

  /**
   * @return Doctrine_Collection
   */
  public function getFamiliesWithCellType()
  {
    return $this->createQuery('f')
      ->leftJoin('f.CellType c')
      ->execute();
  }
}