<?php

/**
 * CellTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CellTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return CellTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CellType');
    }
}