<?php

/**
 * PlaneteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlaneteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlaneteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Planete');
    }
}