<?php

/**
 * PositionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PositionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PositionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Position');
    }
}