<?php

/**
 * VilleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VilleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VilleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ville');
    }
}